Enhance PSScriptAnalyzer configuration and update README with badge

diff --git a/.github/workflows/powershell.yml b/.github/workflows/powershell.yml
--- a/.github/workflows/powershell.yml
+++ b/.github/workflows/powershell.yml
@@ -34,13 +34,19 @@ jobs:
       - name: Run PSScriptAnalyzer
         uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
         with:
-          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
-          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
-          path: .\
+          # Scan only PowerShell files
+          path: '**/*.ps1,**/*.psm1'
           recurse: true
-          # Include your own basic security rules. Removing this option will run all the rules
-          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
+          # Run more security rules
+          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText", "PSAvoidUsingPlainTextForPassword", "PSUseApprovedVerbs"'
           output: results.sarif
+
+      - name: Fail on PSScriptAnalyzer errors
+        run: |
+          if grep -q '"level": "error"' results.sarif; then
+            echo "PSScriptAnalyzer found errors."
+            exit 1
+          fi
 
       # Upload the SARIF file generated in the previous step
       - name: Upload SARIF results file
